spring:
    jpa:
        hibernate.ddl-auto: update
        database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        url: jdbc:h2:mem:auth-db
        driverClassName: org.h2.Driver
        username: sa
        password: password
    h2:
        console:
            enabled: true
            path: /h2-console
jwt:
    secret: PzZmUkF2TzRZN0FwSzlvNzhkQlUwNDNCTklFWFBzYUc=
    expiration: 86400000
springdoc:
    swagger-ui:
        enabled: true
    api-docs:
        path: /v3/api-docs